[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "apexsyslogjs"
description = "The function that fowards log info from the Apex wrapper"
type = "function"
salesforce-api-version = "54.0"
